[font]
size = 12

  [font.normal]
  family = "termfont"
  style = "Regular"

  [font.bold]
  family = "termfont"
  style = "Bold"

  [font.italic]
  family = "termfont"
  style = "Italic"

  [font.bold_italic]
  family = "termfont"
  style = "Bold Italic"
